# Generated by Django 6.0.4 on 2026-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='description',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
